# Generated by Django 3.2.5 on 2021-08-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('avatar', models.CharField(max_length=500, verbose_name='profile photo')),
                ('phone', models.CharField(max_length=15, verbose_name='phone')),
                ('role', models.IntegerField(default=0, verbose_name='role')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='updatedAt')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
