# Generated by Django 3.2.5 on 2021-08-30 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(help_text='The content of a comment on a post', max_length=500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, help_text='Time comment is created', verbose_name='createdAt'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='createdBy',
            field=models.ForeignKey(help_text='Designates the owner of the comment', on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(help_text='The post to which the comment belong', on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, help_text='Time comment is updated', verbose_name='updatedAt'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, help_text='Designates the body of a post', null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='createdBy',
            field=models.ForeignKey(help_text='Designates the owner of a post', on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='isAnonymous',
            field=models.BooleanField(default=False, help_text='Designates if the owner wants to remain anonymous or not'),
        ),
        migrations.AlterField(
            model_name='post',
            name='isSuspended',
            field=models.BooleanField(default=False, help_text='Designates if a post is banned or not'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.CharField(blank=True, help_text='Designates an image of a post', max_length=300, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, help_text='Designates the title of a post', max_length=300, null=True, verbose_name='title'),
        ),
    ]
