# Generated by Django 3.2.5 on 2021-08-30 13:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, help_text='Designates the time of creation of a gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='createdBy',
            field=models.ForeignKey(help_text='Designates the creator of a gallery', on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), help_text='Images of a gallery', size=None),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='tag',
            field=models.CharField(help_text='Describes the name of a gallery by which user can search', max_length=200),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, help_text='Designates the time of update of a gallery'),
        ),
    ]
