# Generated by Django 3.2.5 on 2021-08-21 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('image', models.CharField(blank=True, max_length=300, null=True, verbose_name='image')),
                ('isAnonymous', models.BooleanField(default=False)),
                ('isSuspended', models.BooleanField(default=False)),
                ('isFeatured', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='updatedAt')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
